name: Build and push a docker image

inputs:
  username-github:
    description: User name
    required: true
  password-github:
    description: Password
    required: true
  repo:
    description: Repo
    required: true
  db_password_secret:
    description: DB password secret
    required: true
  brevo_api_key_secret:
    description: Brevo API key
    required: true
  session_secret:
    description: Session secret
    required: true
  opts:
    description: Run time options
    default: --prod
    required: false
  tag:
    description: Tag
    required: true
  registry:
    description: Docker registry
    required: false
    default: ghcr.io
  dockerfile:
    description: Docker file
    required: false
    default: Dockerfile

runs:
  using: 'composite'
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username-github }}
        password: ${{ inputs.password-github }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: ${{ inputs.dockerfile }}
        secret-files: |
          "DB_PASSWORD_SECRET=${{ inputs.db_password_secret }}"
          "BREVO_API_KEY=${{ inputs.brevo_api_key_secret }}"
          "SESSION_SECRET=${{ inputs.session_secret }}"
        build-args: |
          OPTS=${{ inputs.opts }}
        push: true
        tags: ${{ inputs.registry }}/${{ inputs.repo }}:${{ inputs.tag }}
        # CAREFUL of caching as our test and live images will end up the same
        # cache-from: type=gha
        # cache-to: type=gha,mode=max
