name: Publish docker images

on:
  #Â Run if a PR is closed (and has been merged) or on workflow_dispatch
  pull_request:
    branches:
      - main
    types: [closed]

  workflow_dispatch:
    inputs:
      instance:
        description: Instance
        required: true
        default: square-ov
        type: choice
        options:
          - square-ov

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Create secrets folder
        run: |
          mkdir -p secrets

      - name: Store common secrets
        run: |
          echo "${{ secrets.DB_PASSWORD_SECRET }}" > secrets/db_password_secret.txt
          echo "${{ secrets.BREVO_API_KEY }}" > secrets/brevo_api_key_secret.txt
          echo "${{ secrets.SESSION_SECRET }}" > secrets/session_secret.txt

      - name: Build and push with "latest" for square-ov
        if: ${{ github.event.inputs.instance == 'square-ov' || github.event.inputs.instance == 'all' }}
        uses: ./.github/workflows/composites/docker-build-push-version
        with:
          version: square-ov-latest
          username-github: ${{ github.actor }}
          password-github: ${{ secrets.REPO_ACCESS_TOKEN }}
          repo: 'kpturner/square-ov'
